<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateAsetTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('aset', function (Blueprint $table) {
            $table->bigIncrements('id');
            $table->char('referensi',32);
            $table->bigInteger('id_bank')->unsigned();
            $table->text('kas_utama')->nullable();
            $table->text('kas_d1')->nullable();
            $table->text('kas_k1')->nullable();
            $table->text('kas_d2')->nullable();
            $table->text('kas_k2')->nullable();
            $table->text('kas_d3')->nullable();
            $table->text('kas_k3')->nullable();
            $table->text('penempatan_bi_utama')->nullable();
            $table->text('penempatan_bi_d1')->nullable();
            $table->text('penempatan_bi_k1')->nullable();
            $table->text('penempatan_bi_d2')->nullable();
            $table->text('penempatan_bi_k2')->nullable();
            $table->text('penempatan_bi_d3')->nullable();
            $table->text('penempatan_bi_k3')->nullable();
            $table->text('penempatan_lain_utama')->nullable();
            $table->text('penempatan_lain_d1')->nullable();
            $table->text('penempatan_lain_k1')->nullable();
            $table->text('penempatan_lain_d2')->nullable();
            $table->text('penempatan_lain_k2')->nullable();
            $table->text('penempatan_lain_d3')->nullable();
            $table->text('penempatan_lain_k3')->nullable();
            $table->text('suber_utama')->nullable();
            $table->text('suber_d1')->nullable();
            $table->text('suber_k1')->nullable();
            $table->text('suber_d2')->nullable();
            $table->text('suber_k2')->nullable();
            $table->text('suber_d3')->nullable();
            $table->text('suber_k3')->nullable();
            $table->text('kolektibilitas1_utama')->nullable();
            $table->text('kolektibilitas1_d1')->nullable();
            $table->text('kolektibilitas1_k1')->nullable();
            $table->text('kolektibilitas1_d2')->nullable();
            $table->text('kolektibilitas1_k2')->nullable();
            $table->text('kolektibilitas1_d3')->nullable();
            $table->text('kolektibilitas1_k3')->nullable();
            $table->text('kolektibilitas2_utama')->nullable();
            $table->text('kolektibilitas2_d1')->nullable();
            $table->text('kolektibilitas2_k1')->nullable();
            $table->text('kolektibilitas2_d2')->nullable();
            $table->text('kolektibilitas2_k2')->nullable();
            $table->text('kolektibilitas2_d3')->nullable();
            $table->text('kolektibilitas2_k3')->nullable();
            $table->text('kolektibilitas3_utama')->nullable();
            $table->text('kolektibilitas3_d1')->nullable();
            $table->text('kolektibilitas3_k1')->nullable();
            $table->text('kolektibilitas3_d2')->nullable();
            $table->text('kolektibilitas3_k2')->nullable();
            $table->text('kolektibilitas3_d3')->nullable();
            $table->text('kolektibilitas3_k3')->nullable();
            $table->text('kolektibilitas4_utama')->nullable();
            $table->text('kolektibilitas4_d1')->nullable();
            $table->text('kolektibilitas4_k1')->nullable();
            $table->text('kolektibilitas4_d2')->nullable();
            $table->text('kolektibilitas4_k2')->nullable();
            $table->text('kolektibilitas4_d3')->nullable();
            $table->text('kolektibilitas4_k3')->nullable();
            $table->text('kolektibilitas5_utama')->nullable();
            $table->text('kolektibilitas5_d1')->nullable();
            $table->text('kolektibilitas5_k1')->nullable();
            $table->text('kolektibilitas5_d2')->nullable();
            $table->text('kolektibilitas5_k2')->nullable();
            $table->text('kolektibilitas5_d3')->nullable();
            $table->text('kolektibilitas5_k3')->nullable();
            $table->text('penyertaan_utama')->nullable();
            $table->text('penyertaan_d1')->nullable();
            $table->text('penyertaan_k1')->nullable();
            $table->text('penyertaan_d2')->nullable();
            $table->text('penyertaan_k2')->nullable();
            $table->text('penyertaan_d3')->nullable();
            $table->text('penyertaan_k3')->nullable();
            $table->text('ckpnp_utama')->nullable();
            $table->text('ckpnp_d1')->nullable();
            $table->text('ckpnp_k1')->nullable();
            $table->text('ckpnp_d2')->nullable();
            $table->text('ckpnp_k2')->nullable();
            $table->text('ckpnp_d3')->nullable();
            $table->text('ckpnp_k3')->nullable();
            $table->text('astet_utama')->nullable();
            $table->text('astet_d1')->nullable();
            $table->text('astet_k1')->nullable();
            $table->text('astet_d2')->nullable();
            $table->text('astet_k2')->nullable();
            $table->text('astet_d3')->nullable();
            $table->text('astet_k3')->nullable();
            $table->text('akumulasi_utama')->nullable();
            $table->text('akumulasi_d1')->nullable();
            $table->text('akumulasi_k1')->nullable();
            $table->text('akumulasi_d2')->nullable();
            $table->text('akumulasi_k2')->nullable();
            $table->text('akumulasi_d3')->nullable();
            $table->text('akumulasi_k3')->nullable();
            $table->text('properti_utama')->nullable();
            $table->text('properti_d1')->nullable();
            $table->text('properti_k1')->nullable();
            $table->text('properti_d2')->nullable();
            $table->text('properti_k2')->nullable();
            $table->text('properti_d3')->nullable();
            $table->text('properti_k3')->nullable();
            $table->text('ayda_utama')->nullable();
            $table->text('ayda_d1')->nullable();
            $table->text('ayda_k1')->nullable();
            $table->text('ayda_d2')->nullable();
            $table->text('ayda_k2')->nullable();
            $table->text('ayda_d3')->nullable();
            $table->text('ayda_k3')->nullable();
            $table->text('rekening_utama')->nullable();
            $table->text('rekening_d1')->nullable();
            $table->text('rekening_k1')->nullable();
            $table->text('rekening_d2')->nullable();
            $table->text('rekening_k2')->nullable();
            $table->text('rekening_d3')->nullable();
            $table->text('rekening_k3')->nullable();
            $table->text('ckpnl_utama')->nullable();
            $table->text('ckpnl_d1')->nullable();
            $table->text('ckpnl_k1')->nullable();
            $table->text('ckpnl_d2')->nullable();
            $table->text('ckpnl_k2')->nullable();
            $table->text('ckpnl_d3')->nullable();
            $table->text('ckpnl_k3')->nullable();
            $table->text('lain_utama')->nullable();
            $table->text('lain_d1')->nullable();
            $table->text('lain_k1')->nullable();
            $table->text('lain_d2')->nullable();
            $table->text('lain_k2')->nullable();
            $table->text('lain_d3')->nullable();
            $table->text('lain_k3')->nullable();
            $table->string('rekaman')->nullable();
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('aset');
    }
}
